FROM debian:trixie-slim

LABEL org.opencontainers.image.title="SCUM Server"
LABEL org.opencontainers.image.description="Docker image for running a SCUM game server with Wine and SteamCMD on Debian Trixie"
LABEL org.opencontainers.image.version="3.0.0"
LABEL org.opencontainers.image.authors="EvilOlaf"
LABEL org.opencontainers.image.url="https://github.com/EvilOlaf/scum"
LABEL org.opencontainers.image.source="https://github.com/EvilOlaf/scum"
LABEL org.opencontainers.image.base.name="debian:trixie-slim"

WORKDIR /opt

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
	apt-get update && apt-get upgrade -y && apt-get install -y locales && \
	sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN apt-get install -y wget unzip ca-certificates xvfb xauth x11-utils gnupg procps cabextract

RUN wget -O - https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key - && \
	wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/trixie/winehq-trixie.sources && \
	dpkg --add-architecture i386 && \
	apt-get update && \
	apt-get install -y --install-recommends winbind winehq-stable && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN wget --timeout=30 --tries=3 https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz && \
    tar -xvzf steamcmd_linux.tar.gz && \
    rm /opt/steamcmd_linux.tar.gz

ENV WINEDEBUG=-all
ENV WINEARCH=win64
ENV WINEPREFIX=/opt/wine64
ENV XDG_RUNTIME_DIR=/tmp
ENV PATH=/opt/steamcmd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN wineboot --init

RUN wget https://raw.githubusercontent.com/Winetricks/winetricks/refs/tags/20260125/src/winetricks -O winetricks && \
	chmod +x winetricks && \
	sh winetricks -q crypt32 && \
	rm -rf /root/.cache/

COPY start-server.sh /opt/start-server.sh
RUN chmod +x /opt/start-server.sh

ENV GSLT_TOKEN=
CMD ["/opt/start-server.sh"]