apiVersion: v1
entries:
  scum-chart:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-07-11T13:20:52.021042886+02:00"
    description: A Helm chart for deploying SCUM
    digest: cd8fdec9df29c72dadfeaed493501017449e1facf6e8fb14b1d644459c990a18
    name: scum-chart
    type: application
    urls:
    - scum-chart-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-11T13:20:52.020695358+02:00"
